# Generated by Django 4.2.11 on 2024-04-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_movie_watched_by_favoritemovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
